name: Push README to Docker Hub

on:

  workflow_dispatch:

env:
  VERSION: latest
  DKHUB_SLUG: afreisinger/docsify
  GHCR_SLUG: ghcr.io/afreisinger/docsify
  PACKAGE_NAME: docsify

jobs:
  push-readme-to-container:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ env.DKHUB_SLUG }}
          provider: dockerhub
          short_description: 'Docker image for Docsify'
          readme_file: 'README.md'